export const LOAD_TIMETABLE_REQUEST = "LOAD_TIMETABLE_REQUEST";
export const LOAD_TIMETABLE_FAILURE = "LOAD_TIMETABLE_FAILURE";
export const LOAD_TIMETABLE_SUCCESS = "LOAD_TIMETABLE_SUCCESS";

export const CHANGE_GROUP = "CHANGE_GROUP";
export const LOAD_CONFIGURATION = "LOAD_CONFIGURATION";
export const CHANGE_FILTER = "CHANGE_FILTER";
export const CHANGE_CONFIGURATION_OPTION = "CHANGE_CONFIGURATION_OPTION";

export const SET_CURRENT_DAY = "SET_CURRENT_DAY";
export const SET_DAY = "SET_DAY";
